### ISSUE TITLE
SimpleCompiler Variable Bug

### ISSUE THREAD

**Issue by cvogt729** [janino-compiler/janino#172]
I found a bug in Janino 3.1.7 as downloaded from the Maven repository. To reproduce the bug, use `org.codehaus.janino.SimpleCompiler` to compile the following class:

```java
public class test {
  public static void main(String[] args){
    String s;
    if (Boolean.FALSE || (s="Hello World!")==null){
      return;
    }
    System.out.println(s);
  }
}
```

I expect `Hello World!` to be printed to the console (note that `javac` does this). Instead Janino throws the following error:
```
Exception in thread "main" org.codehaus.commons.compiler.InternalCompilerException: Compiling "test" in File 'test.java', Line 1, Column 8: File 'test.java', Line 2, Column 22: Compiling "main(String[] args)": File 'test.java', Line 7, Column 16: org.codehaus.commons.compiler.InternalCompilerException: File 'test.java', Line 7, Column 16: Compiling "System.out.println(s)": File 'test.java', Line 7, Column 24: Compiling "s": Invalid local variable index 1
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:375)
        at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:339)
        at org.codehaus.janino.UnitCompiler$1.visitCompilationUnit(UnitCompiler.java:336)
        at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:370)
        at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:336)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:254)
        at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:491)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:232)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:210)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:70)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:59)
        at org.codehaus.janino.SimpleCompiler.<init>(SimpleCompiler.java:149)
        at org.codehaus.janino.SimpleCompiler.main(SimpleCompiler.java:112)
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test.java', Line 2, Column 22: Compiling "main(String[] args)": File 'test.java', Line 7, Column 16: org.codehaus.commons.compiler.InternalCompilerException: File 'test.java', Line 7, Column 16: Compiling "System.out.println(s)": File 'test.java', Line 7, Column 24: Compiling "s": Invalid local variable index 1
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3239)
        at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1389)
        at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1362)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:806)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:418)
        at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:397)
        at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:392)
        at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1687)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:392)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:365)
        ... 13 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test.java', Line 7, Column 16: org.codehaus.commons.compiler.InternalCompilerException: File 'test.java', Line 7, Column 16: Compiling "System.out.println(s)": File 'test.java', Line 7, Column 24: Compiling "s": Invalid local variable index 1
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2405)
        at org.codehaus.janino.UnitCompiler.access$1800(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$5.visitExpressionStatement(UnitCompiler.java:1528)
        at org.codehaus.janino.UnitCompiler$5.visitExpressionStatement(UnitCompiler.java:1521)
        at org.codehaus.janino.Java$ExpressionStatement.accept(Java.java:3206)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1521)
        at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1605)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3560)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3235)
        ... 23 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test.java', Line 7, Column 16: Compiling "System.out.println(s)": File 'test.java', Line 7, Column 24: Compiling "s": Invalid local variable index 1
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5765)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3966)
        at org.codehaus.janino.UnitCompiler.access$6000(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$10.visitMethodInvocation(UnitCompiler.java:3941)
        at org.codehaus.janino.UnitCompiler$10.visitMethodInvocation(UnitCompiler.java:3913)
        at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5459)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3913)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2403)
        ... 31 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test.java', Line 7, Column 24: Compiling "s": Invalid local variable index 1
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5765)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5246)
        at org.codehaus.janino.UnitCompiler.access$9200(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$13.visitMethodInvocation(UnitCompiler.java:4620)
        at org.codehaus.janino.UnitCompiler$13.visitMethodInvocation(UnitCompiler.java:4593)
        at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5459)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4593)
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5763)
        ... 38 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Invalid local variable index 1
        at org.codehaus.janino.UnitCompiler.getLocalVariableTypeInfo(UnitCompiler.java:13390)
        at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12421)
        at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12396)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4668)
        at org.codehaus.janino.UnitCompiler.access$8100(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$13$1.visitLocalVariableAccess(UnitCompiler.java:4605)
        at org.codehaus.janino.UnitCompiler$13$1.visitLocalVariableAccess(UnitCompiler.java:4597)
        at org.codehaus.janino.Java$LocalVariableAccess.accept(Java.java:4650)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4597)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4593)
        at org.codehaus.janino.Java$Lvalue.accept(Java.java:4517)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4593)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4664)
        at org.codehaus.janino.UnitCompiler.access$7600(UnitCompiler.java:234)
        at org.codehaus.janino.UnitCompiler$13$1.visitAmbiguousName(UnitCompiler.java:4600)
        at org.codehaus.janino.UnitCompiler$13$1.visitAmbiguousName(UnitCompiler.java:4597)
        at org.codehaus.janino.Java$AmbiguousName.accept(Java.java:4592)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4597)
        at org.codehaus.janino.UnitCompiler$13.visitLvalue(UnitCompiler.java:4593)
        at org.codehaus.janino.Java$Lvalue.accept(Java.java:4517)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4593)
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5763)
        ... 45 more
```

In case it is relevant, I used the SimpleCompiler command-line utility from Windows PowerShell with OpenJDK 11.0.14.1.
```powershell
java '-cp' 'janino-3.1.7.jar;commons-compiler-3.1.7.jar' 'org.codehaus.janino.SimpleCompiler' 'test.java' 'test'
```

While this may seem like a contrived example, it arose from a script I've written at work. My original script actually threw an `Operand stack underflow` error, but `Invalid local variable` is what occurred when I tried to boil down the issue. I suspect both have similar root causes.

**Comment by cvogt729** [comment]
I glanced at the test case you made. I haven't taken the time to delve into how the test cases are executed, but I have a concern about how it was written. If your test case demonstrates the bug, it shouldn't compile at all. If your test case does not demonstrate the bug, then it should `return false`. Instead of checking for either of those results, it says `assertCompilationUnitMainReturnsTrue()`.

Also, it shouldn't matter that `Boolean.FALSE` is a constant value. If we replace it with some complicated method `func()` that could return `true` or `false`, then it should still compile and execute just fine. If `func()` is `true`, then we go to the if-statement body due to `||` short-circuit evaluation, which immediately returns, so there are no attempts to reference the uninitialized variable `s`. If `func()` is `false`, then `s` is set to `"Hello World"`, and `s` is printed to the console.

Thank you!

**Comment by aunkrig** [comment]
No, if you replace `Boolean.FALSE` with a non-const expression, then the code should not compile with JAVAC, because in the line of the `println()`, the local variable `s` is still unassigned. The JLS dictates that.

**Comment by cvogt729** [comment]
Perhaps there is some misunderstanding. The code provided below positively compiles and executes using the JAVAC and JAVA commands provided by the JDK. If you don't believe me, try it yourself.
```java
class test {
  public static void main(String[] args){
    String s;
    if (f(Integer.parseInt(args[0])) || (s="Hello World!")==null){
      System.out.println("No references to s have been made.");
      return;
    }
    System.out.println(s);
  }
  public static boolean f(int x){
    boolean b = true;
    for (int i=0;i<x;++i){
      b^=true;
    }
    return b;
  }
}
```
Of course, you need to give it a parameter that parses as an integer. For example, if `4` is the parameter, it prints `No references to s have been made`. If `5` is the parameter, it prints `Hello World!`. The output of `java --version` in my command prompt yields:
```
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
```

**Comment by aunkrig** [comment]
I still believe that your code should not compile, and I absolutely do not understand why JAVAC (7, 8, 11, 17) compiles it, and `s` is initialized to `"No references to s have been made."`. According to the JLS, the local variable reference in the `println` line *is an error*, because `s` is not "defintely assigned" at this place. I expect that other compilers (e.g. other versions of JAVAC) will report an error here.

By no means you should rely on this JAVAC bug and you should instead fix your code, e.g. initialize `s`.

**Comment by cvogt729** [comment]
It is not a bug in JAVAC. The code should compile and execute. `s` is not initialized to `"No references to s have been made"`. `s` is not initialized at all in that case. The `return` statement inside the `if` block seems to be where the misunderstanding is occurring. The `return` statement exits the `main` method before the `System.out.println(s)` statement is ever reached. It would be logically equivalent to have `System.out.println(s)` inside of an `else` block for that `if` statement.

**Comment by cvogt729** [comment]
I do not believe this issue is resolved. I would like opinions from other developers familiar with the Janino repository if you know of anyone appropriate. I will walk through the flow analysis for this code line-by-line.
```java
/* 01 */ class test {
/* 02 */   public static void main(String[] args){
/* 03 */     boolean b = args.length>0 && args[0].equals("0");
/* 04 */     String s;
/* 05 */     if (b || (s="Hello World!")==null){
/* 06 */       System.out.println("No references to s have been made.");
/* 07 */       return;
/* 08 */     }
/* 09 */     System.out.println(s);
/* 10 */   }
/* 11 */ }
```
- Flow Analysis
  (Line 02) The `main` method is invoked.
  (Line 03) `b` is set to either `true` or `false` depending on arguments given to the program.
  (Line 04) A `String` variable `s` is declared but not initialized.
  - First Possibility: `b==true`
    (Line 05) The `if` statement [short-circuits](https://en.wikipedia.org/wiki/Short-circuit_evaluation), and we go to the body of the `if` block. Note that `s` remains uninitialized.
    (Line 06) Print `No references to s have been made.` to the console.
    (Line 07) The `return` statement exits the `main` method, and the program terminates.
  - Second Possibility: `b==false`
    (Line 05) `s` is initialized to `Hello World!`. Since `s!=null`, the `if` statement fails.
    (Line 09) `s` is printed to the console.
    (Line 10) The program terminates.

The whole point: It is impossible to reach line 09 without first initializing `s`. The JAVAC flow analysis logic realizes this, and Janino should as well. If your JLS fails to detect this, then it is a problem with your JLS.

**Comment by aunkrig** [comment]
Hey Cameron,

now I had the time to look thoroughly into this issue, and found that I had been a bit confused... So: You are absolutely right, Janino _should_ recognize that `s` is defnitely assigned after the `if` statement, and should compile the code without errors, which it doesn't.

The point is that it is quite difficult to determine that `s` is definitely assigned, and Janino fails to do that. I will check whether I can improved Janino (with reasonable effort and complexity). Stay tuned.

I added your test case to the regression test suite.

**Comment by aunkrig** [comment]
I believe I fixed it... was easier than expected.

Please test!

**Comment by cvogt729** [comment]
Thank you! I'm away from my computer for a few days, but I'll test it next week.

**Comment by cvogt729** [comment]
This source code still throws a compilation error:
```java
public class test1 {
  public static void main(String[] args){
    boolean b = args.length>0 && args[0].equals("0");
    String s;
    if (b || (s="Hello World!")==null){
      System.out.println("No references to s have been made.");
      return;
    }
    System.out.println(s);
  }
}
```
<details>
<summary>StackTrace</summary>

```
Exception in thread "main" org.codehaus.commons.compiler.InternalCompilerException: Compiling "test1" in File 'test1.java', Line 1, Column 17: File 'test1.java', Line 2, Column 31: Compiling "main(String[] args)"
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:401)
        at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:362)
        at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:360)
        at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:371)
        at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:360)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:264)
        at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:517)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:241)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:219)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:70)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:59)
        at org.codehaus.janino.SimpleCompiler.<init>(SimpleCompiler.java:158)
        at org.codehaus.janino.SimpleCompiler.main(SimpleCompiler.java:121)
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test1.java', Line 2, Column 31: Compiling "main(String[] args)"
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3293)
        at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1429)
        at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1402)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:828)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:441)
        at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:421)
        at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:417)
        at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1688)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:417)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:391)
        ... 12 more
Caused by: java.lang.RuntimeException: File 'test1.java', Line 9, Column 25
        at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1644)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3617)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3289)
        ... 21 more
Caused by: java.lang.RuntimeException: File 'test1.java', Line 9, Column 25
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1586)
        at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1642)
        ... 23 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test1.java', Line 9, Column 25
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2486)
        at org.codehaus.janino.UnitCompiler$6.visitExpressionStatement(UnitCompiler.java:1562)
        at org.codehaus.janino.UnitCompiler$6.visitExpressionStatement(UnitCompiler.java:1557)
        at org.codehaus.janino.Java$ExpressionStatement.accept(Java.java:3209)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1557)
        ... 24 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test1.java', Line 9, Column 25: Compiling "System.out.println(s)"
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5810)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:4044)
        at org.codehaus.janino.UnitCompiler$13.visitMethodInvocation(UnitCompiler.java:4019)
        at org.codehaus.janino.UnitCompiler$13.visitMethodInvocation(UnitCompiler.java:3994)
        at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5470)
        at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3994)
        at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2484)
        ... 28 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: File 'test1.java', Line 9, Column 33: Compiling "s"
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5810)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5314)
        at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4689)
        at org.codehaus.janino.UnitCompiler$16.visitMethodInvocation(UnitCompiler.java:4665)
        at org.codehaus.janino.Java$MethodInvocation.accept(Java.java:5470)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4665)
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5808)
        ... 34 more
Caused by: org.codehaus.commons.compiler.InternalCompilerException: Invalid local variable index 2
        at org.codehaus.janino.UnitCompiler.getLocalVariableTypeInfo(UnitCompiler.java:13474)
        at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12488)
        at org.codehaus.janino.UnitCompiler.load(UnitCompiler.java:12463)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4736)
        at org.codehaus.janino.UnitCompiler$16$1.visitLocalVariableAccess(UnitCompiler.java:4675)
        at org.codehaus.janino.UnitCompiler$16$1.visitLocalVariableAccess(UnitCompiler.java:4669)
        at org.codehaus.janino.Java$LocalVariableAccess.accept(Java.java:4661)
        at org.codehaus.janino.UnitCompiler$16.visitLvalue(UnitCompiler.java:4669)
        at org.codehaus.janino.UnitCompiler$16.visitLvalue(UnitCompiler.java:4665)
        at org.codehaus.janino.Java$Lvalue.accept(Java.java:4528)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4665)
        at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:4732)
        at org.codehaus.janino.UnitCompiler$16$1.visitAmbiguousName(UnitCompiler.java:4670)
        at org.codehaus.janino.UnitCompiler$16$1.visitAmbiguousName(UnitCompiler.java:4669)
        at org.codehaus.janino.Java$AmbiguousName.accept(Java.java:4603)
        at org.codehaus.janino.UnitCompiler$16.visitLvalue(UnitCompiler.java:4669)
        at org.codehaus.janino.UnitCompiler$16.visitLvalue(UnitCompiler.java:4665)
        at org.codehaus.janino.Java$Lvalue.accept(Java.java:4528)
        at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4665)
        at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5808)
        ... 40 more
```

</details>

However, this code does not throw an error:
```java
public class test1 {
  public static boolean main(String[] args){
    boolean b = args.length>0 && args[0].equals("0");
    String s;
    if (b || (s="Hello World!")==null){
      System.out.println("No references to s have been made.");
      return true;
    }
    System.out.println(s);
    return false;
  }
}
```
It seems the `void` return type is the remaining edge-case to fix.

**Comment by aunkrig** [comment]
You are completely right; the StackMap was not cleared after the RETURN instruction. Please re-test.

**Comment by cvogt729** [comment]
Everything looks good to me!

**Comment by cvogt729** [comment]
Thanks for the new Janino release. If you're curious as to what I'm using Janino for, see <https://github.com/automatic-controls/commissioning-scripts>. WebCTRL is software used to control commercial HVAC equipment.  I've made a WebCTRL add-on which allows users to upload and execute scripts for various purposes. Users may precompile their scripts into `.jar` archives, or they may directly upload `.java` files to be compiled by Janino at runtime.
